# github.com/flipped-aurora/gin-vue-admin/server Global Configuration

# jwt configuration
jwt:
  signing-key: freebns
  expires-time: 7d
  buffer-time: 1d
  issuer: freebns
# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[free-bns]"
  director: storage/logs
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: 127.0.0.1:6379
  password:

# email configuration
email:
  to: xxx@qq.com
  port: 465
  from: lll2669877481@163.com
  host: smtp.163.com
  is-ssl: true
  secret: ZXENDGUOMAZDTGIH
  nickname: free-bns中文社区

# system configuration
system:
  env: develop # Change to "develop" to skip authentication for development mode
  addr: 8080
  host: http://localhost:8080
  db-type: mysql
  oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-redis: true # 使用redis
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 1500
  #  IP限制一个小时
  iplimit-time: 3600
  #  路由全局前缀
  router-prefix: "/"

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效
  is-email-or-pic: 0 # 是否开启邮箱或图片验证码 0 全部 1 仅图片验证码 2 仅邮箱验证码

Database:
  LogZap: true
  Master:
    DBType: mysql
    DBName: freebns
    UserName: root
    Password: root
    Host: 127.0.0.1:3306
    TablePrefix: bbs_
    Charset: utf8mb4
    ParseTime: true
    MaxIdleConns: 10
    MaxOpenConns: 30
  Slave:
    DBType: mysql
    DBName: ""
    UserName: ""
    Password: ""
    Host: ""
    TablePrefix: ""
    Charset: utf8mb4
    ParseTime: true
    MaxIdleConns: 10
    MaxOpenConns: 30
# local configuration
local:
  path: storage/uploads/file
  store-path: storage/uploads/file
  upload-path: https://www.5ixiaohui.com/upload

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: ZoneHuaDong
  bucket: "freebns"
  img-path: "https://www.5ixiaohui.com"
  use-https: true
  access-key: "DQy3SgdA_8tUtlWd9mksE7yJSQakFw0WHvHJTXGv"
  secret-key: "876i6rFFeIWwSagcOaMkA6KjVALe_Ui_NdrlmRm1"
  use-cdn-domains: true

# aliyun oss configuration
aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath

# tencent cos configuration
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# aws s3 configuration (minio compatible)
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# huawei obs configuration
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key

# excel configuration
excel:
  dir: ./storage/files/excel/

elasticsearch:
  host: 127.0.0.1
  port: 9200
  user:
  password:
  enable: false